name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
        default: true
        components: llvm-tools-preview

    - uses: Swatinem/rust-cache@v1
    
    - name: Install other dependencies
      run: |
        cargo install rustfilt 
        cargo install cargo-binutils
        cargo install --git https://github.com/izderadicka/badge-maker.git --branch fix-serde-import --features cli
        sudo apt install jq
    
    - uses: actions/checkout@v2

    - name: Calculate coverage
      id: coverage-calculation
      run: ./coverage.sh

    - name: Creates coverage badge
      run: | 
        echo "Coverage is ${{ steps.coverage-calculation.outputs.coverage }}"
        badge-maker coverage ${{ steps.coverage-calculation.outputs.coverage }} -c informational -l #282828 -s flat > coverage/badge.svg

    - name: Upload to wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "coverage"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
      
    
