name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
        default: true
        components: llvm-tools-preview
    
    - name: Install other dependencies
      run: |
        cargo install rustfilt 
        cargo install cargo-binutils
        sudo apt install jq
    
    - uses: actions/checkout@v2

    - name: Calculate coverage
      id: coverage-calculation
      run: ./coverage.sh

    - name: Creates coverage badge
      run: echo "Coverage is ${{ steps.coverage-calculation.coverage }}"
    
